// Parameters.js
import "./UserFormFields.css";
const parameters = {
  formFields: [
    { id: "name", label: "Adı", type: "text", placeholder: "Ad giriniz.." },
    {
      id: "surname",
      label: "Soyadı",
      type: "text",
      placeholder: "Soyad giriniz..",
    },
    {
      id: "gender",
      label: "Cinsiyeti",
      type: "select",
      placeholder: "Cinsiyet seçiniz..",
      options: [
        { value: "male", label: "Erkek" },
        { value: "female", label: "Kadın" },
      ],
    },
    {
      id: "email",
      label: "E-posta Adresi",
      type: "email",
      placeholder: "Mail adresi giriniz..",
    },
    {
      id: "phone",
      label: "Telefon Numarası",
      type: "tel",
      placeholder: "Telefon numarası giriniz..",
    },
    {
      id: "address",
      label: "Adres",
      type: "textarea",
      placeholder: "Adres giriniz..",
    },
    {
      id: "meslek",
      label: "Meslek",
      type: "textarea",
      placeholder: "Meslek giriniz..",
    },
    { id: "age", label: "Yaşı", type: "number", placeholder: "Yaş giriniz.." },
    {
      id: "height",
      label: "Boyu (cm)",
      type: "number",
      placeholder: "Boy giriniz..",
    },
    {
      id: "weight",
      label: "Ağırlığı (kg)",
      type: "number",
      placeholder: "Kilo giriniz..",
    },
    {
      id: "targetWeight",
      label: "Hedef Ağırlığı (kg)",
      type: "number",
      placeholder: "Hedef kilo giriniz..",
    },
    {
      id: "bki",
      label: "BKİ",
      type: "number",
      placeholder: "BKİ..",
      readOnly: true,
      value: "",
    },
    {
      id: "bkiReferance",
      label: "BKİ Referans Aralığı",
      type: "number",
      placeholder: "BKİ referans aralığı..",
    },
    {
      id: "anamnesis",
      label: "Anamnez",
      type: "textarea",
      placeholder: "Anamnez giriniz..",
    },
    {
      id: "diagnosis",
      label: "Tanısı",
      type: "text",
      placeholder: "Tanı giriniz..",
    },
    {
      id: "chronicDiseases",
      label: "Kronik Hastalıkları",
      type: "text",
      placeholder: "Kronik hastalıkları giriniz..",
      chronicDiseasesItems: [],
    },
    {
      id: "bloodIndicators",
      label: "Önemli Kan Bulguları",
      type: "text",
      placeholder: "Önemli kan bulgularını giriniz..",
      options: [
        { value: "hba1c", label: "HbA1c" },
        { value: "glikoz", label: "Glikoz" },
        { value: "insulin", label: "İnsülin" },
        { value: "t3", label: "T3" },
        { value: "t4", label: "T4" },
        { value: "tsh", label: "TSH" },
        { value: "antitpo", label: "ANTİ TPO" },
        { value: "antitg", label: "ANTİ-TG" },
        { value: "kolestrol", label: "KOLESTROL" },
        { value: "trigliserid", label: "TRİGLİSERİD" },
        { value: "hdl", label: "HDL" },
        { value: "ldl", label: "LDL" },
        { value: "ferritin", label: "FERRİTTİN" },
        { value: "b12", label: "B12" },
        { value: "dvit", label: "D VİT" },
        { value: "alt", label: "ALT" },
        { value: "ast", label: "AST" },
        { value: "ure", label: "ÜRE" },
        { value: "urikasit", label: "ÜRİK ASİT" },
        { value: "cinko", label: "ÇİNKO" },
        { value: "selenyum", label: "SELENYUM" },
        { value: "folikasit", label: "FOLİK ASİT" },
      ],
      items: [],
    },
    {
      id: "medications",
      label: "Kullandığı İlaçlar",
      type: "text",
      placeholder: "Kullandığı ilaçları giriniz..",
      medicationsItems: [],
    },
    {
      id: "alergies",
      label: "Alerjiler",
      type: "text",
      placeholder: "Alerjiler giriniz..",
      alergiesItems: [],
    },
    {
      id: "dailySleepTime",
      label: "Günlük Uyku Süresi",
      type: "number",
      placeholder: "Günlük uyku süresi giriniz..",
    },
    {
      id: "vitamins",
      label: "Vitamin Takviyeleri",
      type: "text",
      placeholder: "Vitamin takviyeleri giriniz..",
    },
    {
      id: "sport",
      label: "Haftada kaç gün spor yapıyorsun?",
      type: "text",
      placeholder: "Haftada kaç gün spor yapıyorsun?",
    },
    {
      id: "totalEnergyNeeds",
      label: "Toplam Enerji Gereksinmesi (kcal)",
      type: "number",
      placeholder: "Toplam enerji gereksinmesini..",
    },
    {
      id: "bmh",
      label: "Bazal Metabolizma Hızı (kcal)",
      type: "number",
      placeholder: "Bazal metabolizma hızı..",
    },
    {
      id: "physicalActivity",
      label: "Fiziksel Aktivite Düzeyi",
      placeholder: "Fiziksel aktivite düzeyi",
      type: "select",
      options: [
        { value: "sedentary", label: "Sedanter (Az veya hiç egzersiz)" },
        {
          value: "lightlyActive",
          label: "Hafif Aktif (Hafif egzersiz 1-3 gün)",
        },
        {
          value: "moderatelyActive",
          label: "Orta Aktif (Orta düzeyde egzersiz 3-5 gün)",
        },
        { value: "veryActive", label: "Çok Aktif (Güçlü egzersiz 6-7 gün)" },
      ],
    },

    {
      id: "travelFrequency",
      label: "Seyahat Sıklığı",
      type: "select",
      placeholder: "Seyahat sıklığı seçiniz..",
      options: [
        { value: "rarely", label: "Nadiren" },
        { value: "occasionally", label: "Ara sıra" },
        { value: "frequently", label: "Sıkça" },
        { value: "regularly", label: "Düzenli olarak" },
      ],
    },
    {
      id: "dietRelatedDiseases",
      label: "Diyet Listesine Etki Eden Hastalıklar",
      type: "select",
      placeholder: "Hastalık seçiniz..",
      options: [
        { id: "bulimia", label: "Bulimia" },
        { id: "anorexia", label: "Anoreksiya" },
        { id: "obesity", label: "Obezite" },
        { id: "diabetes", label: "Diyabet" },
        { id: "fattyLiver", label: "Karaciğer Yağlanması" },
        { id: "celiac", label: "Çölyak" },
        { id: "noDisease", label: "Etken Bir Hastalık Bulunmamaktadır" },
      ],
    },
    { id: "note", label: "Not", type: "text", placeholder: "Notlar giriniz.." },
  ],
};

export default parameters;
